# Generated by Django 3.2.7 on 2021-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='salt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
