# Generated by Django 3.2.7 on 2021-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_passwordmanager_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='passwordmanager',
            name='salt',
            field=models.CharField(default='', max_length=256),
        ),
    ]
