# Generated by Django 3.2.7 on 2021-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20211003_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='salt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
