# Generated by Django 3.2.7 on 2021-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_passwordmanager_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='salt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
