# Generated by Django 3.2.7 on 2021-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_passwordmanager_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='changingPass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='passwordmanager',
            name='key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='passwordmanager',
            name='salt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
